version: "3.8"

services:
  nethermind:
    image: nethermind/nethermind:latest
    container_name: nethermind
    restart: unless-stopped
    volumes:
      - nethermind-data:/nethermind
      - ./engine.jwt:/engine.jwt
    ports:
      - "8545:8545"   # HTTP RPC
      - "8546:8546"   # WebSocket RPC
      - "8551:8551"   # Engine API (para consenso)
      - "30303:30303/tcp"  # P2P
      - "30303:30303/udp"  # P2P
    command: [
      "--config=mainnet",
      "--datadir=/nethermind",
      "--JsonRpc.Enabled=true",
      "--JsonRpc.Host=0.0.0.0",
      "--JsonRpc.Port=8545",
      "--JsonRpc.EngineHost=0.0.0.0",
      "--JsonRpc.EnginePort=8551",
      "--JsonRpc.JwtSecretFile=/engine.jwt",
      "--Sync.SnapSync=true",
      "--Init.StoreReceipts=false",
      "--Sync.AncientBodiesBarrier=2100000",
      "--Network.MaxActivePeers=70",
      "--Network.DiscoveryPort=30303",
      "--Network.P2PPort=30303",
      "--Pruning.Mode=Full",
      "--Pruning.CacheMb=2048",
      "--Pruning.FullPruningCompletionBehavior=ShutdownOnSuccess",
      "--HealthChecks.Enabled=true",
      "--JsonRpc.EnabledModules=eth,TxPool,net,web3",
      "--Network.Bootnodes=enode://...@ip:port,enode://...@ip:port"

    ]
    depends_on:
      - lighthouse

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    volumes:
      - lighthouse-data:/root/.lighthouse
      - ./engine.jwt:/engine.jwt
    ports:
      - "5052:5052"
      - "9000:9000/tcp"      # P2P TCP
      - "9001:9001/udp"      # P2P QUIC
    command: >
      lighthouse bn
      --network mainnet
      --datadir /root/.lighthouse
      --execution-endpoint http://nethermind:8551
      --execution-jwt /engine.jwt
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
      --disable-upnp

volumes:
  nethermind-data:
  lighthouse-data:
