version: "3.8"

services:
  nethermind:
    image: nethermind/nethermind:latest
    container_name: nethermind
    restart: unless-stopped
    volumes:
      - nethermind-data:/nethermind
      - ./engine.jwt:/engine.jwt
    ports:
      - "8545:8545"   # HTTP RPC
      - "8546:8546"   # WebSocket RPC
      - "8551:8551"   # Engine API (para consenso)
    command: [
      "--config=mainnet",
      "--datadir=/nethermind",
      "--JsonRpc.Enabled=true",
      "--JsonRpc.Host=0.0.0.0",
      "--JsonRpc.Port=8545",
      "--JsonRpc.EngineHost=0.0.0.0",
      "--JsonRpc.EnginePort=8551",
      "--JsonRpc.JwtSecretFile=/engine.jwt",
      "--Sync.SnapSync=true",
      "--Sync.AncientBodiesBarrier=11000000",
      "--Sync.AncientReceiptsBarrier=11000000",
      "--Sync.DownloadBodiesInFastSync=true",
      "--Sync.DownloadReceiptsInFastSync=true",
      "--Network.MaxActivePeers=100",
      "--Network.DiscoveryPort=30303",
      "--Network.P2PPort=30303",
      "--Pruning.Mode=Hybrid",
      "--HealthChecks.Enabled=true",
    ]
    depends_on:
      - lighthouse

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    volumes:
      - lighthouse-data:/root/.lighthouse
      - ./engine.jwt:/engine.jwt
    ports:
      - "5052:5052"
    command: >
      lighthouse bn
      --network mainnet
      --datadir /root/.lighthouse
      --execution-endpoint http://nethermind:8551
      --execution-jwt /engine.jwt
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io

volumes:
  nethermind-data:
  lighthouse-data:
